# Generated by Django 5.2.9 on 2025-12-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharepointcredentials',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='sharepointcredentials',
            name='client_secret',
        ),
        migrations.RemoveField(
            model_name='sharepointcredentials',
            name='tenant_id',
        ),
        migrations.AddField(
            model_name='sharepointcredentials',
            name='access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharepointcredentials',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharepointcredentials',
            name='refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
